import { supabase } from "@/lib/supabaseClient";
const unwrap=({data,error})=>{if(error)throw error;return data;};
const uiRate=(r)=>({...r,label:r.name||"Standard Shipping",description:r.min_delivery_days!=null&&r.max_delivery_days!=null?`${r.min_delivery_days}–${r.max_delivery_days} business days`:""});
export const shippingAdminApi={
 async load(){const [profiles,rates,packages,settings]=await Promise.all([supabase.from("shipping_profiles").select("*").order("priority",{ascending:true}),supabase.from("shipping_rates").select("*").order("priority",{ascending:true}),supabase.from("shipping_packages").select("*").order("is_default",{ascending:false}).order("name"),supabase.from("delivery_settings").select("*").eq("id",1).maybeSingle()]);return{profiles:unwrap(profiles)||[],rates:(unwrap(rates)||[]).map(uiRate),packages:unwrap(packages)||[],settings:unwrap(settings)||null};},
 async saveSettings(d){return unwrap(await supabase.from("delivery_settings").upsert({id:1,local_pickup_enabled:Boolean(d.local_pickup_enabled),pickup_name:d.pickup_name||"Local Pickup",pickup_location:d.pickup_location||"GDP Clothing — Saskatoon",pickup_instructions:d.pickup_instructions||null,processing_min_days:Math.max(0,Number(d.processing_min_days||0)),processing_max_days:Math.max(0,Number(d.processing_max_days||0)),carrier_rates_enabled:Boolean(d.carrier_rates_enabled),carrier_name:d.carrier_name||"Canada Post",fallback_rate_enabled:Boolean(d.fallback_rate_enabled),fallback_rate:Math.max(0,Number(d.fallback_rate||0)),updated_at:new Date().toISOString()}).select().single());},
 async saveProfile(p){const x={name:p.name||"General shipping",description:p.description||null,active:p.active!==false,product_scope:p.product_scope||"all",origin_location:p.origin_location||{},product_ids:p.product_ids||[],priority:Number(p.priority||100),updated_at:new Date().toISOString()};if(p.id)return unwrap(await supabase.from("shipping_profiles").update(x).eq("id",p.id).select().single());return unwrap(await supabase.from("shipping_profiles").insert(x).select().single());},
 async saveRate(r){let minDays=r.min_delivery_days,maxDays=r.max_delivery_days;const m=String(r.description||"").match(/(\d+)\D+(\d+)/);if(m){minDays=Number(m[1]);maxDays=Number(m[2]);}const x={profile_id:r.profile_id,method_code:r.method_code||"standard",name:r.label||r.name||"Standard Shipping",price:Math.max(0,Number(r.price||0)),min_order:r.min_order===""||r.min_order==null?null:Number(r.min_order),max_order:r.max_order===""||r.max_order==null?null:Number(r.max_order),min_delivery_days:Math.max(0,Number(minDays??3)),max_delivery_days:Math.max(0,Number(maxDays??7)),conditions:r.conditions||{},zone_name:r.zone_name||"Canada",country_codes:r.country_codes?.length?r.country_codes:["CA"],province_codes:r.province_codes||[],postal_patterns:r.postal_patterns||[],min_weight_grams:r.min_weight_grams===""||r.min_weight_grams==null?null:Number(r.min_weight_grams),max_weight_grams:r.max_weight_grams===""||r.max_weight_grams==null?null:Number(r.max_weight_grams),rate_source:r.rate_source||"manual",fallback_price:r.fallback_price===""||r.fallback_price==null?null:Number(r.fallback_price),priority:Number(r.priority||100),active:r.active!==false,updated_at:new Date().toISOString()};if(r.id)return unwrap(await supabase.from("shipping_rates").update(x).eq("id",r.id).select().single());return unwrap(await supabase.from("shipping_rates").insert(x).select().single());},
 async deleteRate(id){return unwrap(await supabase.from("shipping_rates").delete().eq("id",id));},
 async savePackage(p){const x={name:p.name||"Package",package_type:p.package_type||"mailer",length_cm:Math.max(0,Number(p.length_cm||0)),width_cm:Math.max(0,Number(p.width_cm||0)),height_cm:Math.max(0,Number(p.height_cm||0)),empty_weight_grams:Math.max(0,Number(p.empty_weight_grams||0)),is_default:Boolean(p.is_default),active:p.active!==false,updated_at:new Date().toISOString()};if(p.is_default)await supabase.from("shipping_packages").update({is_default:false}).neq("id",p.id||"00000000-0000-0000-0000-000000000000");if(p.id)return unwrap(await supabase.from("shipping_packages").update(x).eq("id",p.id).select().single());return unwrap(await supabase.from("shipping_packages").insert(x).select().single());}
};
