import React, { useEffect, useState } from "react";
import { Bot, RefreshCw, ShieldCheck, TrendingUp } from "lucide-react";
import { aiBusinessManagerApi } from "@/lib/aiBusinessManagerApi";

function Metric({ label, value }) { return <div className="rounded-xl border border-[#dedfe3] bg-white p-4"><div className="text-xs font-bold uppercase tracking-wide text-[#70737a]">{label}</div><div className="mt-1 text-2xl font-bold tabular-nums">{value}</div></div>; }
const severityClass={high:"border-red-200 bg-red-50",medium:"border-amber-200 bg-amber-50",info:"border-slate-200 bg-slate-50"};

export default function AiBusinessManagerModule(){
 const[snapshot,setSnapshot]=useState(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);setError("");try{setSnapshot(await aiBusinessManagerApi.loadSummary())}catch(err){setError(err?.message||"Could not load Business Manager.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]); const s=snapshot?.summary||{},b=snapshot?.briefing||{},t=b.trend||{},priorities=b.priorities||[];
 return <main className="max-w-[1600px] mx-auto px-4 md:px-7 lg:px-10 py-6 space-y-5">
  <div className="rounded-2xl border border-[#dedfe3] bg-white p-5 flex flex-col md:flex-row md:items-center gap-4 md:justify-between"><div><div className="flex items-center gap-2 font-bold"><Bot size={20}/> AI Business Manager</div><p className="mt-1 text-sm text-[#60636a]">Phase 1.1 is strictly read-only. It summarizes business signals, priorities and trends without changing production data.</p></div><button onClick={load} disabled={loading} className="h-10 px-4 rounded-lg border border-[#d6d8dd] bg-white hover:bg-[#f7f7f8] disabled:opacity-50 inline-flex items-center justify-center gap-2 text-sm font-semibold"><RefreshCw size={16} className={loading?"animate-spin":""}/> Refresh</button></div>
  {error?<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>:null}
  <section className="rounded-2xl border border-[#dedfe3] bg-white p-5"><div className="flex items-center gap-2"><ShieldCheck size={19}/><h2 className="font-bold">Today’s business briefing</h2></div><p className="mt-2 text-sm text-[#555961]">{b.headline||"Loading read-only briefing…"}</p><div className="mt-4 grid grid-cols-3 gap-2"><Metric label="Orders · 7 days" value={t.ordersLast7Days??"—"}/><Metric label="Previous 7 days" value={t.ordersPrevious7Days??"—"}/><Metric label="Paid · 7 days" value={t.paidOrdersLast7Days??"—"}/></div></section>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Metric label="Orders" value={s.orders??"—"}/><Metric label="Paid orders" value={s.paidOrders??"—"}/><Metric label="Paid revenue" value={Number.isFinite(Number(s.paidRevenueRecorded))?`$${Number(s.paidRevenueRecorded).toFixed(2)}`:"—"}/><Metric label="Products" value={s.products??"—"}/><Metric label="Variants" value={s.variants??"—"}/><Metric label="Available units" value={s.inventoryAvailable??"—"}/><Metric label="Sales leads" value={s.salesLeads??"—"}/><Metric label="Support tickets" value={s.supportTickets??"—"}/></div>
  <section className="rounded-2xl border border-[#dedfe3] bg-white p-5"><div className="flex items-center gap-2"><TrendingUp size={19}/><h2 className="font-bold">What should I focus on today?</h2></div><div className="mt-3 space-y-2">{priorities.length?priorities.map((p,i)=><div key={`${p.title}-${i}`} className={`rounded-xl border p-3 ${severityClass[p.severity]||severityClass.info}`}><div className="flex items-center gap-2"><span className="text-[10px] uppercase tracking-wide font-bold">{p.severity}</span><strong className="text-sm">{p.title}</strong></div><p className="mt-1 text-sm text-[#555961]">{p.detail}</p></div>):<div className="rounded-xl bg-[#f6f7f8] p-3 text-sm">No summary-level attention items detected.</div>}</div></section>
  <div className="text-xs text-[#777b82]">Security mode: admin-only · JWT required · deterministic read-only recommendations · no customer PII returned · no write actions.</div>
 </main>;
}
