import React, { useEffect, useMemo, useState } from "react";
import { Package, Plus, Save, Truck, MapPin, Trash2 } from "lucide-react";
import { shippingAdminApi } from "@/lib/shippingAdminApi";

const box = "bg-white border border-[#e1e3e5] rounded-xl";
const input = "w-full border border-[#c9cccf] rounded-lg px-3 py-2 text-sm bg-white";
const provinces = ["AB","BC","MB","NB","NL","NS","NT","NU","ON","PE","QC","SK","YT"];
const csv = value => String(value || "").split(",").map(x => x.trim().toUpperCase()).filter(Boolean);

function RateEditor({ rate, patchRate, saveRate, removeRate }) {
  return <div className="border rounded-xl p-4 grid lg:grid-cols-12 gap-3 items-end">
    <label className="lg:col-span-2 text-xs">Rate name<input className={input} value={rate.label || ""} onChange={e=>patchRate(rate.id,{label:e.target.value})}/></label>
    <label className="lg:col-span-2 text-xs">Zone<input className={input} value={rate.zone_name || "Canada"} onChange={e=>patchRate(rate.id,{zone_name:e.target.value})}/></label>
    <label className="lg:col-span-2 text-xs">Provinces<input className={input} placeholder="SK, AB or blank=all" value={(rate.province_codes||[]).join(", ")} onChange={e=>patchRate(rate.id,{province_codes:csv(e.target.value).filter(x=>provinces.includes(x))})}/></label>
    <label className="lg:col-span-2 text-xs">Postal patterns<input className={input} placeholder="S7*, S0K*" value={(rate.postal_patterns||[]).join(", ")} onChange={e=>patchRate(rate.id,{postal_patterns:csv(e.target.value)})}/></label>
    <label className="lg:col-span-1 text-xs">Min $<input type="number" className={input} value={rate.min_order ?? ""} onChange={e=>patchRate(rate.id,{min_order:e.target.value})}/></label>
    <label className="lg:col-span-1 text-xs">Max $<input type="number" className={input} value={rate.max_order ?? ""} onChange={e=>patchRate(rate.id,{max_order:e.target.value})}/></label>
    <label className="lg:col-span-1 text-xs">Price<input type="number" step="0.01" className={input} value={rate.price ?? 0} onChange={e=>patchRate(rate.id,{price:e.target.value})}/></label>
    <div className="lg:col-span-1 flex gap-2"><button onClick={()=>saveRate(rate)} className="border rounded-lg p-2" aria-label={`Save ${rate.label || "shipping rate"}`}><Save size={16}/></button><button onClick={()=>removeRate(rate)} className="border rounded-lg p-2 text-red-600" aria-label={`Remove ${rate.label || "shipping rate"}`}><Trash2 size={16}/></button></div>
    <label className="lg:col-span-3 text-xs">Delivery description<input className={input} value={rate.description || ""} onChange={e=>patchRate(rate.id,{description:e.target.value})}/></label>
    <label className="lg:col-span-2 text-xs">Min weight (g)<input type="number" className={input} value={rate.min_weight_grams ?? ""} onChange={e=>patchRate(rate.id,{min_weight_grams:e.target.value})}/></label>
    <label className="lg:col-span-2 text-xs">Max weight (g)<input type="number" className={input} value={rate.max_weight_grams ?? ""} onChange={e=>patchRate(rate.id,{max_weight_grams:e.target.value})}/></label>
    <label className="lg:col-span-2 text-xs">Source<select className={input} value={rate.rate_source || "manual"} onChange={e=>patchRate(rate.id,{rate_source:e.target.value})}><option value="manual">Manual</option><option value="carrier">Carrier calculated</option></select></label>
    <label className="lg:col-span-2 text-xs flex items-center gap-2 pb-2"><input type="checkbox" checked={rate.active!==false} onChange={e=>patchRate(rate.id,{active:e.target.checked})}/> Active</label>
  </div>;
}

export default function ShippingDeliveryManager({ notify = (message) => void message }) {
  const [data, setData] = useState({ profiles: [], rates: [], packages: [], settings: null, products: [] });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [productSearch, setProductSearch] = useState("");
  const [weightSearch, setWeightSearch] = useState("");
  const load = async () => { setLoading(true); try { setData(await shippingAdminApi.load()); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const settings = data.settings || { local_pickup_enabled:true, pickup_name:"Local Pickup", pickup_location:"GDP Clothing — Saskatoon", processing_min_days:1, processing_max_days:2, carrier_rates_enabled:false, carrier_name:"Canada Post", fallback_rate_enabled:true, fallback_rate:12.99 };
  const general = useMemo(() => data.profiles.find(p => p.product_scope === "all" && p.active !== false) || data.profiles.find(p => p.product_scope === "all") || null, [data.profiles]);
  const customProfiles = useMemo(() => data.profiles.filter(p => p.product_scope !== "all"), [data.profiles]);
  const visibleProducts = useMemo(() => { const term=productSearch.trim().toLowerCase(); return data.products.filter(p=>p.status!=="archived"&&(!term||`${p.name} ${p.slug||""} ${p.category||""}`.toLowerCase().includes(term))); }, [data.products, productSearch]);
  const visibleWeightProducts = useMemo(() => { const term=weightSearch.trim().toLowerCase(); return data.products.filter(p=>p.status!=="archived"&&(!term||`${p.name} ${p.slug||""} ${p.category||""}`.toLowerCase().includes(term))); }, [data.products, weightSearch]);
  const assignedByProduct = useMemo(() => { const map=new Map(); for(const profile of [...customProfiles].sort((a,b)=>Number(a.priority||100)-Number(b.priority||100))){for(const id of profile.product_ids||[]){if(!map.has(id))map.set(id,profile);}} return map; }, [customProfiles]);
  const ratesFor = profileId => data.rates.filter(r => r.profile_id === profileId);
  const patchSettings = patch => setData(d => ({ ...d, settings: { ...(d.settings || settings), ...patch } }));
  const patchRate = (id, patch) => setData(d => ({ ...d, rates: d.rates.map(r => r.id === id ? { ...r, ...patch } : r) }));
  const patchProfile = (id, patch) => setData(d => ({ ...d, profiles: d.profiles.map(p => p.id === id ? { ...p, ...patch } : p) }));
  const patchPackage = (id, patch) => setData(d => ({ ...d, packages:d.packages.map(p => p.id === id ? { ...p, ...patch } : p) }));
  const patchProduct = (id, patch) => setData(d => ({ ...d, products:d.products.map(p => p.id === id ? { ...p, ...patch } : p) }));
  const saveSettings = async () => { setSaving(true); try { await shippingAdminApi.saveSettings(settings); notify("Shipping settings saved."); await load(); } finally { setSaving(false); } };
  const saveProfile = async profile => { setSaving(true); try { if(profile.product_scope === "all") await shippingAdminApi.saveProfile(profile); else await shippingAdminApi.saveProfiles(data.profiles.filter(p=>p.product_scope!=="all")); notify("Shipping profile saved."); await load(); } finally { setSaving(false); } };
  const toggleProduct = (profileId, productId, checked) => setData(d => ({ ...d, profiles:d.profiles.map(profile => { if(profile.product_scope === "all") return profile; const current=new Set(profile.product_ids||[]); if(profile.id===profileId && checked) current.add(productId); else if(profile.id===profileId || checked) current.delete(productId); return { ...profile, product_ids:[...current] }; }) }));
  const addRate = async profileId => { setSaving(true); try { await shippingAdminApi.saveRate({ profile_id:profileId, method_code:"standard", label:"Standard Shipping", description:"3–7 business days", price:12.99, min_order:0, max_order:null, zone_name:"Canada", country_codes:["CA"], province_codes:[], postal_patterns:[], rate_source:"manual", priority:100, active:true }); notify("Shipping rate added."); await load(); } finally { setSaving(false); } };
  const addProfile = async () => { setSaving(true); try { const profile=await shippingAdminApi.saveProfile({ name:"New custom profile", description:"Assign products, adjust rates, then activate.", product_scope:"selected", product_ids:[], priority:100+customProfiles.length*10, active:false }); await shippingAdminApi.saveRate({profile_id:profile.id,method_code:"standard",label:"Standard Shipping",description:"3–7 business days",price:12.99,min_order:0,max_order:149.99,zone_name:"Canada",country_codes:["CA"],province_codes:[],postal_patterns:[],rate_source:"manual",priority:100,active:true}); await shippingAdminApi.saveRate({profile_id:profile.id,method_code:"standard",label:"Free Standard Shipping",description:"3–7 business days",price:0,min_order:150,max_order:null,zone_name:"Canada",country_codes:["CA"],province_codes:[],postal_patterns:[],rate_source:"manual",priority:100,active:true}); notify("Custom shipping profile created. It is inactive until you enable it."); await load(); } finally { setSaving(false); } };
  const saveRate = async rate => { setSaving(true); try { await shippingAdminApi.saveRate(rate); notify("Shipping rate saved."); await load(); } finally { setSaving(false); } };
  const removeRate = async rate => { setSaving(true); try { await shippingAdminApi.deleteRate(rate.id); notify("Shipping rate removed."); await load(); } finally { setSaving(false); } };
  const addPackage = async () => { setSaving(true); try { await shippingAdminApi.savePackage({ name:"New package", package_type:"mailer", active:true }); notify("Package added."); await load(); } finally { setSaving(false); } };
  const savePackage = async pkg => { setSaving(true); try { await shippingAdminApi.savePackage(pkg); notify("Package saved."); await load(); } finally { setSaving(false); } };
  const saveProductWeight = async product => { setSaving(true); try { await shippingAdminApi.saveProductWeight(product); notify(`${product.name} shipping weight saved.`); await load(); } finally { setSaving(false); } };

  if (loading) return <div className="py-10 text-sm text-[#6d7175]">Loading Shipping & Delivery…</div>;
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Shipping & Delivery</h2><p className="text-sm text-[#6d7175] mt-1">Shopify-style profiles, zones, rates, pickup, packages and carrier fallback controls.</p></div><button disabled={saving} onClick={saveSettings} className="bg-[#202223] text-white rounded-lg px-4 py-2 text-sm font-medium flex items-center gap-2"><Save size={15}/> Save settings</button></div>

    {general && <section className={`${box} p-5`}><div className="flex items-center gap-2 font-semibold"><Truck size={18}/> General shipping profile</div><p className="text-xs text-[#6d7175] mt-1">Unassigned shippable products use <strong>{general.name}</strong>. Custom profiles below override it only for their assigned products.</p><div className="mt-4 space-y-3">{ratesFor(general.id).map(rate=><RateEditor key={rate.id} rate={rate} patchRate={patchRate} saveRate={saveRate} removeRate={removeRate}/>)}<button onClick={()=>addRate(general.id)} className="border rounded-lg px-3 py-2 text-sm flex items-center gap-2"><Plus size={15}/> Add general rate</button></div></section>}

    <section className={`${box} p-5`}>
      <div className="flex flex-wrap items-center justify-between gap-3"><div><div className="font-semibold">Custom product shipping profiles</div><p className="text-xs text-[#6d7175] mt-1">Assign products to a custom profile. Mixed carts combine the applicable profile shipping charges.</p></div><button disabled={saving} onClick={addProfile} className="border rounded-lg px-3 py-2 text-sm flex items-center gap-2"><Plus size={15}/> Add custom profile</button></div>
      {!customProfiles.length && <div className="mt-4 rounded-lg border border-dashed p-5 text-sm text-[#6d7175]">No custom product profiles yet. All shippable products use the general profile.</div>}
      <div className="mt-4 space-y-5">{customProfiles.map(profile => <div key={profile.id} className="rounded-xl border p-4 space-y-4">
        <div className="grid md:grid-cols-[minmax(0,1fr)_minmax(0,2fr)_auto] gap-3 items-end"><label className="text-xs">Profile name<input className={input} value={profile.name||""} onChange={e=>patchProfile(profile.id,{name:e.target.value})}/></label><label className="text-xs">Description<input className={input} value={profile.description||""} onChange={e=>patchProfile(profile.id,{description:e.target.value})}/></label><button disabled={saving} onClick={()=>saveProfile(profile)} className="bg-[#202223] text-white rounded-lg px-3 py-2 text-sm flex items-center justify-center gap-2"><Save size={14}/> Save profile</button></div>
        <div className="flex flex-wrap items-center gap-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={profile.active!==false} onChange={e=>patchProfile(profile.id,{active:e.target.checked})}/> Active</label><span className="text-xs text-[#6d7175]">{(profile.product_ids||[]).length} product(s) assigned</span><span className="text-xs text-[#6d7175]">Deactivate to return assigned products to General shipping without deleting this setup.</span></div>
        <div className="rounded-lg bg-[#f6f6f7] p-4"><div className="font-medium text-sm">Product assignments</div><input className={`${input} mt-2`} placeholder="Search products" value={productSearch} onChange={e=>setProductSearch(e.target.value)}/><div className="mt-3 grid md:grid-cols-2 gap-2 max-h-56 overflow-y-auto">{visibleProducts.map(product=>{const checked=(profile.product_ids||[]).includes(product.id);const owner=assignedByProduct.get(product.id);return <label key={product.id} className={`flex gap-3 rounded-lg border bg-white p-3 text-sm ${checked?"border-[#202223]":"border-[#e1e3e5]"}`}><input type="checkbox" checked={checked} onChange={e=>toggleProduct(profile.id,product.id,e.target.checked)}/><span className="min-w-0"><span className="font-medium block truncate">{product.name}</span><span className="text-[11px] text-[#6d7175]">{product.category||product.selling_mode||"Product"}{owner&&!checked?` · Currently ${owner.name}`:""}</span></span></label>;})}</div></div>
        <div><div className="font-medium text-sm mb-2">Profile rates</div><div className="space-y-3">{ratesFor(profile.id).map(rate=><RateEditor key={rate.id} rate={rate} patchRate={patchRate} saveRate={saveRate} removeRate={removeRate}/>)}<button onClick={()=>addRate(profile.id)} className="border rounded-lg px-3 py-2 text-sm flex items-center gap-2"><Plus size={15}/> Add profile rate</button></div></div>
      </div>)}</div>
    </section>

    <section className={`${box} p-5`}>
      <div><div className="font-semibold">Product shipping weights</div><p className="text-xs text-[#6d7175] mt-1">Enter the packed item weight in grams. Checkout multiplies this by quantity and adds the default package weight once per shipping-profile shipment. Weight-restricted rates are ignored when any product in that shipment has no weight.</p></div>
      <input className={`${input} mt-4`} placeholder="Search products by name, slug or category" value={weightSearch} onChange={e=>setWeightSearch(e.target.value)}/>
      <div className="mt-3 grid md:grid-cols-2 gap-3">{visibleWeightProducts.map(product=><div key={product.id} className="rounded-xl border p-3 flex items-end gap-3"><div className="min-w-0 flex-1"><div className="font-medium text-sm truncate">{product.name}</div><div className="text-[11px] text-[#6d7175] truncate">{product.category||product.selling_mode||"Product"}</div><label className="block text-xs mt-2">Weight per item (g)<input type="number" min="0" step="1" className={input} placeholder="Not set" value={product.weight ?? ""} onChange={e=>patchProduct(product.id,{weight:e.target.value,weight_unit:"g"})}/></label></div><button disabled={saving} onClick={()=>saveProductWeight(product)} className="border rounded-lg px-3 py-2 text-sm flex items-center gap-2"><Save size={14}/> Save</button></div>)}</div>
    </section>

    <div className="grid lg:grid-cols-2 gap-5"><section className={`${box} p-5`}><div className="flex items-center gap-2 font-semibold"><MapPin size={18}/> Local pickup</div><div className="space-y-3 mt-4"><label className="flex gap-2 text-sm"><input type="checkbox" checked={settings.local_pickup_enabled} onChange={e=>patchSettings({local_pickup_enabled:e.target.checked})}/> Enable local pickup</label><input className={input} value={settings.pickup_name||""} onChange={e=>patchSettings({pickup_name:e.target.value})}/><input className={input} value={settings.pickup_location||""} onChange={e=>patchSettings({pickup_location:e.target.value})}/><textarea className={input} placeholder="Pickup instructions" value={settings.pickup_instructions||""} onChange={e=>patchSettings({pickup_instructions:e.target.value})}/></div></section><section className={`${box} p-5`}><div className="font-semibold">Delivery estimates & carrier fallback</div><div className="grid grid-cols-2 gap-3 mt-4"><label className="text-xs">Processing min days<input type="number" className={input} value={settings.processing_min_days} onChange={e=>patchSettings({processing_min_days:e.target.value})}/></label><label className="text-xs">Processing max days<input type="number" className={input} value={settings.processing_max_days} onChange={e=>patchSettings({processing_max_days:e.target.value})}/></label></div><label className="flex gap-2 text-sm mt-4"><input type="checkbox" checked={settings.carrier_rates_enabled} onChange={e=>patchSettings({carrier_rates_enabled:e.target.checked})}/> Enable carrier-calculated rates when integration is configured</label><input className={`${input} mt-3`} value={settings.carrier_name||"Canada Post"} onChange={e=>patchSettings({carrier_name:e.target.value})}/><label className="flex gap-2 text-sm mt-3"><input type="checkbox" checked={settings.fallback_rate_enabled} onChange={e=>patchSettings({fallback_rate_enabled:e.target.checked})}/> Use fallback rate if carrier is unavailable</label><label className="block text-xs mt-3">Fallback CAD<input type="number" step="0.01" className={input} value={settings.fallback_rate} onChange={e=>patchSettings({fallback_rate:e.target.value})}/></label></section></div>
    <section className={`${box} p-5`}><div className="flex items-center justify-between"><div className="flex items-center gap-2 font-semibold"><Package size={18}/> Packages</div><button onClick={addPackage} className="border rounded-lg px-3 py-2 text-sm flex items-center gap-2"><Plus size={15}/> Add package</button></div><div className="grid lg:grid-cols-2 gap-3 mt-4">{data.packages.map(pkg=><div key={pkg.id} className="border rounded-xl p-4 space-y-3"><input className={input} value={pkg.name} onChange={e=>patchPackage(pkg.id,{name:e.target.value})}/><div className="grid grid-cols-4 gap-2">{[["length_cm","L cm"],["width_cm","W cm"],["height_cm","H cm"],["empty_weight_grams","Weight g"]].map(([k,l])=><label key={k} className="text-[10px]">{l}<input type="number" className={input} value={pkg[k]} onChange={e=>patchPackage(pkg.id,{[k]:e.target.value})}/></label>)}</div><label className="flex gap-2 text-sm"><input type="checkbox" checked={pkg.is_default} onChange={e=>patchPackage(pkg.id,{is_default:e.target.checked})}/> Default package</label><button onClick={()=>savePackage(pkg)} className="border rounded-lg px-3 py-2 text-sm flex items-center gap-2"><Save size={14}/> Save package</button></div>)}</div></section>
  </div>;
}
