import React, { useEffect, useMemo, useState } from "react";
import { Package, Plus, Save, Truck, MapPin, Trash2 } from "lucide-react";
import { shippingAdminApi } from "@/lib/shippingAdminApi";

const box = "bg-white border border-[#e1e3e5] rounded-xl";
const input = "w-full border border-[#c9cccf] rounded-lg px-3 py-2 text-sm bg-white";
const provinces = ["AB","BC","MB","NB","NL","NS","NT","NU","ON","PE","QC","SK","YT"];
const csv = value => String(value || "").split(",").map(x => x.trim().toUpperCase()).filter(Boolean);

export default function ShippingDeliveryManager({ notify = (message) => void message }) {
  const [data, setData] = useState({ profiles: [], rates: [], packages: [], settings: null });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); try { setData(await shippingAdminApi.load()); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const settings = data.settings || { local_pickup_enabled:true, pickup_name:"Local Pickup", pickup_location:"GDP Clothing — Saskatoon", processing_min_days:1, processing_max_days:2, carrier_rates_enabled:false, carrier_name:"Canada Post", fallback_rate_enabled:true, fallback_rate:12.99 };
  const general = data.profiles[0];
  const rates = useMemo(() => data.rates.filter(r => !general || r.profile_id === general.id), [data.rates, general]);
  const patchSettings = patch => setData(d => ({ ...d, settings: { ...settings, ...patch } }));
  const patchRate = (id, patch) => setData(d => ({ ...d, rates: d.rates.map(r => r.id === id ? { ...r, ...patch } : r) }));
  const saveSettings = async () => { setSaving(true); try { await shippingAdminApi.saveSettings(settings); notify("Shipping settings saved."); await load(); } finally { setSaving(false); } };
  const ensureProfile = async () => general || shippingAdminApi.saveProfile({ name:"General shipping", code:"general", priority:10, active:true });
  const addRate = async () => { setSaving(true); try { const p = await ensureProfile(); await shippingAdminApi.saveRate({ profile_id:p.id, method_code:"standard", label:"Standard Shipping", description:"3–7 business days", price:12.99, zone_name:"Canada", country_codes:["CA"], province_codes:[], postal_patterns:[], rate_source:"manual", priority:100, active:true }); notify("Shipping rate added."); await load(); } finally { setSaving(false); } };
  const saveRate = async rate => { setSaving(true); try { await shippingAdminApi.saveRate(rate); notify("Shipping rate saved."); await load(); } finally { setSaving(false); } };
  const removeRate = async rate => { setSaving(true); try { await shippingAdminApi.deleteRate(rate.id); notify("Shipping rate removed."); await load(); } finally { setSaving(false); } };
  const addPackage = async () => { setSaving(true); try { await shippingAdminApi.savePackage({ name:"New package", package_type:"mailer", active:true }); notify("Package added."); await load(); } finally { setSaving(false); } };
  const savePackage = async pkg => { setSaving(true); try { await shippingAdminApi.savePackage(pkg); notify("Package saved."); await load(); } finally { setSaving(false); } };
  const patchPackage = (id, patch) => setData(d => ({ ...d, packages:d.packages.map(p => p.id === id ? { ...p, ...patch } : p) }));

  if (loading) return <div className="py-10 text-sm text-[#6d7175]">Loading Shipping & Delivery…</div>;
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Shipping & Delivery</h2><p className="text-sm text-[#6d7175] mt-1">Shopify-style profiles, zones, rates, pickup, packages and carrier fallback controls.</p></div><button disabled={saving} onClick={saveSettings} className="bg-[#202223] text-white rounded-lg px-4 py-2 text-sm font-medium flex items-center gap-2"><Save size={15}/> Save settings</button></div>
    <section className={`${box} p-5`}><div className="flex items-center gap-2 font-semibold"><Truck size={18}/> General shipping profile</div><p className="text-xs text-[#6d7175] mt-1">All shippable products use this profile unless assigned to a custom profile.</p><div className="mt-4 space-y-3">
      {rates.map(rate => <div key={rate.id} className="border rounded-xl p-4 grid lg:grid-cols-12 gap-3 items-end">
        <label className="lg:col-span-2 text-xs">Rate name<input className={input} value={rate.label || ""} onChange={e=>patchRate(rate.id,{label:e.target.value})}/></label><label className="lg:col-span-2 text-xs">Zone<input className={input} value={rate.zone_name || "Canada"} onChange={e=>patchRate(rate.id,{zone_name:e.target.value})}/></label><label className="lg:col-span-2 text-xs">Provinces<input className={input} placeholder="SK, AB or blank=all" value={(rate.province_codes||[]).join(", ")} onChange={e=>patchRate(rate.id,{province_codes:csv(e.target.value).filter(x=>provinces.includes(x))})}/></label><label className="lg:col-span-2 text-xs">Postal patterns<input className={input} placeholder="S7*, S0K*" value={(rate.postal_patterns||[]).join(", ")} onChange={e=>patchRate(rate.id,{postal_patterns:csv(e.target.value)})}/></label><label className="lg:col-span-1 text-xs">Min $<input type="number" className={input} value={rate.min_order ?? ""} onChange={e=>patchRate(rate.id,{min_order:e.target.value})}/></label><label className="lg:col-span-1 text-xs">Max $<input type="number" className={input} value={rate.max_order ?? ""} onChange={e=>patchRate(rate.id,{max_order:e.target.value})}/></label><label className="lg:col-span-1 text-xs">Price<input type="number" step="0.01" className={input} value={rate.price ?? 0} onChange={e=>patchRate(rate.id,{price:e.target.value})}/></label><div className="lg:col-span-1 flex gap-2"><button onClick={()=>saveRate(rate)} className="border rounded-lg p-2"><Save size={16}/></button><button onClick={()=>removeRate(rate)} className="border rounded-lg p-2 text-red-600"><Trash2 size={16}/></button></div>
        <label className="lg:col-span-3 text-xs">Delivery description<input className={input} value={rate.description || ""} onChange={e=>patchRate(rate.id,{description:e.target.value})}/></label><label className="lg:col-span-2 text-xs">Min weight (g)<input type="number" className={input} value={rate.min_weight_grams ?? ""} onChange={e=>patchRate(rate.id,{min_weight_grams:e.target.value})}/></label><label className="lg:col-span-2 text-xs">Max weight (g)<input type="number" className={input} value={rate.max_weight_grams ?? ""} onChange={e=>patchRate(rate.id,{max_weight_grams:e.target.value})}/></label><label className="lg:col-span-2 text-xs">Source<select className={input} value={rate.rate_source || "manual"} onChange={e=>patchRate(rate.id,{rate_source:e.target.value})}><option value="manual">Manual</option><option value="carrier">Carrier calculated</option></select></label><label className="lg:col-span-2 text-xs flex items-center gap-2 pb-2"><input type="checkbox" checked={rate.active!==false} onChange={e=>patchRate(rate.id,{active:e.target.checked})}/> Active</label>
      </div>)}<button onClick={addRate} className="border rounded-lg px-3 py-2 text-sm flex items-center gap-2"><Plus size={15}/> Add rate</button>
    </div></section>
    <div className="grid lg:grid-cols-2 gap-5"><section className={`${box} p-5`}><div className="flex items-center gap-2 font-semibold"><MapPin size={18}/> Local pickup</div><div className="space-y-3 mt-4"><label className="flex gap-2 text-sm"><input type="checkbox" checked={settings.local_pickup_enabled} onChange={e=>patchSettings({local_pickup_enabled:e.target.checked})}/> Enable local pickup</label><input className={input} value={settings.pickup_name||""} onChange={e=>patchSettings({pickup_name:e.target.value})}/><input className={input} value={settings.pickup_location||""} onChange={e=>patchSettings({pickup_location:e.target.value})}/><textarea className={input} placeholder="Pickup instructions" value={settings.pickup_instructions||""} onChange={e=>patchSettings({pickup_instructions:e.target.value})}/></div></section><section className={`${box} p-5`}><div className="font-semibold">Delivery estimates & carrier fallback</div><div className="grid grid-cols-2 gap-3 mt-4"><label className="text-xs">Processing min days<input type="number" className={input} value={settings.processing_min_days} onChange={e=>patchSettings({processing_min_days:e.target.value})}/></label><label className="text-xs">Processing max days<input type="number" className={input} value={settings.processing_max_days} onChange={e=>patchSettings({processing_max_days:e.target.value})}/></label></div><label className="flex gap-2 text-sm mt-4"><input type="checkbox" checked={settings.carrier_rates_enabled} onChange={e=>patchSettings({carrier_rates_enabled:e.target.checked})}/> Enable carrier-calculated rates when integration is configured</label><input className={`${input} mt-3`} value={settings.carrier_name||"Canada Post"} onChange={e=>patchSettings({carrier_name:e.target.value})}/><label className="flex gap-2 text-sm mt-3"><input type="checkbox" checked={settings.fallback_rate_enabled} onChange={e=>patchSettings({fallback_rate_enabled:e.target.checked})}/> Use fallback rate if carrier is unavailable</label><label className="block text-xs mt-3">Fallback CAD<input type="number" step="0.01" className={input} value={settings.fallback_rate} onChange={e=>patchSettings({fallback_rate:e.target.value})}/></label></section></div>
    <section className={`${box} p-5`}><div className="flex items-center justify-between"><div className="flex items-center gap-2 font-semibold"><Package size={18}/> Packages</div><button onClick={addPackage} className="border rounded-lg px-3 py-2 text-sm flex items-center gap-2"><Plus size={15}/> Add package</button></div><div className="grid lg:grid-cols-2 gap-3 mt-4">{data.packages.map(pkg=><div key={pkg.id} className="border rounded-xl p-4 space-y-3"><input className={input} value={pkg.name} onChange={e=>patchPackage(pkg.id,{name:e.target.value})}/><div className="grid grid-cols-4 gap-2">{[["length_cm","L cm"],["width_cm","W cm"],["height_cm","H cm"],["empty_weight_grams","Weight g"]].map(([k,l])=><label key={k} className="text-[10px]">{l}<input type="number" className={input} value={pkg[k]} onChange={e=>patchPackage(pkg.id,{[k]:e.target.value})}/></label>)}</div><label className="flex gap-2 text-sm"><input type="checkbox" checked={pkg.is_default} onChange={e=>patchPackage(pkg.id,{is_default:e.target.checked})}/> Default package</label><button onClick={()=>savePackage(pkg)} className="border rounded-lg px-3 py-2 text-sm flex items-center gap-2"><Save size={14}/> Save package</button></div>)}</div></section>
  </div>;
}
