
create table if not exists public.messenger_agent_settings (
  id smallint primary key default 1 check (id = 1),
  enabled boolean not null default true,
  business_name text not null default 'GDP Clothing',
  agent_name text not null default 'GDP Assistant',
  website_url text not null default 'https://gdpclothing.ca',
  custom_studio_url text not null default 'https://gdpclothing.ca/custom-studio',
  greeting text not null default 'Hi! 👋 Welcome to GDP Clothing. I can help with products, prices, custom orders, shipping, pickup, discounts, and website links.',
  fallback_reply text not null default 'I’m not fully sure about that. You can browse GDP Clothing at https://gdpclothing.ca, or type “human” and I’ll leave this conversation for a team member.',
  human_handoff_reply text not null default 'I’ll leave this conversation for a GDP Clothing team member so you can get an accurate answer. Please send any helpful details, such as your order number if this is about an order.',
  handoff_timeout_minutes integer not null default 720 check (handoff_timeout_minutes between 15 and 10080),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messenger_agent_knowledge (
  id bigint generated by default as identity primary key,
  intent text not null unique,
  keywords text[] not null default '{}'::text[],
  response_template text not null,
  priority integer not null default 0,
  requires_human boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messenger_agent_events (
  event_key text primary key,
  sender_hash text not null,
  event_type text not null,
  intent text,
  status text not null default 'received'
    check (status in ('received','replied','handoff','ignored','error')),
  error_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messenger_agent_handoffs (
  psid text primary key,
  reason text,
  status text not null default 'open' check (status in ('open','resolved')),
  opened_at timestamptz not null default now(),
  expires_at timestamptz not null,
  last_customer_message_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.messenger_agent_settings enable row level security;
alter table public.messenger_agent_knowledge enable row level security;
alter table public.messenger_agent_events enable row level security;
alter table public.messenger_agent_handoffs enable row level security;

revoke all on table public.messenger_agent_settings from anon, authenticated;
revoke all on table public.messenger_agent_knowledge from anon, authenticated;
revoke all on table public.messenger_agent_events from anon, authenticated;
revoke all on table public.messenger_agent_handoffs from anon, authenticated;

grant select, insert, update, delete on table public.messenger_agent_settings to service_role;
grant select, insert, update, delete on table public.messenger_agent_knowledge to service_role;
grant select, insert, update, delete on table public.messenger_agent_events to service_role;
grant select, insert, update, delete on table public.messenger_agent_handoffs to service_role;
grant usage, select on sequence public.messenger_agent_knowledge_id_seq to service_role;

create index if not exists messenger_agent_knowledge_active_priority_idx
  on public.messenger_agent_knowledge (active, priority desc);
create index if not exists messenger_agent_events_created_at_idx
  on public.messenger_agent_events (created_at desc);
create index if not exists messenger_agent_handoffs_status_expires_idx
  on public.messenger_agent_handoffs (status, expires_at);

comment on table public.messenger_agent_settings is
  'Server-only configuration for GDP Clothing Facebook Messenger auto-reply agent.';
comment on table public.messenger_agent_knowledge is
  'Server-only editable deterministic Messenger knowledge. No paid LLM is required for normal replies.';
comment on table public.messenger_agent_events is
  'Privacy-minimized Messenger event log used for deduplication and diagnostics. Raw customer message text is not stored.';
comment on table public.messenger_agent_handoffs is
  'Server-only temporary Messenger handoff state. PSID is retained only to suppress automation while a human handles the conversation.';

insert into public.messenger_agent_settings (id)
values (1)
on conflict (id) do nothing;

insert into public.messenger_agent_knowledge
  (intent, keywords, response_template, priority, requires_human, active)
values
  (
    'greeting',
    array['hello','hi','hey','good morning','good afternoon','good evening','kumusta','musta'],
    'Hi! 👋 Welcome to GDP Clothing. I can help with products, prices, custom orders, shipping, pickup, discounts, and website links. What are you looking for?',
    100,
    false,
    true
  ),
  (
    'custom_design',
    array['custom','customize','customise','personalized','personalised','artwork','photo','logo','design my shirt','design my hoodie'],
    'Yes — you can create your own design in GDP Clothing Custom Studio: {{custom_studio_url}}',
    90,
    false,
    true
  ),
  (
    'discounts',
    array['discount','promo','promotion','coupon','sale','discount code','promo code'],
    'I can check the current active GDP Clothing discount codes for you.',
    80,
    false,
    true
  ),
  (
    'payment',
    array['payment','credit card','debit card','stripe','affirm','paypal','pay online'],
    'Payment options shown at checkout are handled through secure payment providers. GDP Clothing does not ask you to send card or bank details through Messenger.',
    75,
    false,
    true
  ),
  (
    'hours',
    array['hours','open','opening','close','closing','business hours'],
    'Our current business hours are shown on the GDP Clothing Facebook Page. If you are planning a pickup, send the day you have in mind and a team member can confirm availability.',
    60,
    false,
    true
  ),
  (
    'thanks',
    array['thanks','thank you','salamat','ty'],
    'You’re welcome! 😊 If you need anything else for your order or custom design, just message GDP Clothing here.',
    50,
    false,
    true
  ),
  (
    'human',
    array['human','person','agent','representative','owner','talk to someone','speak to someone'],
    '{{human_handoff_reply}}',
    200,
    true,
    true
  ),
  (
    'order_support',
    array['order status','where is my order','track order','tracking','refund','return','cancel order','cancellation','chargeback','dispute','wrong order','damaged order','payment problem','charged twice'],
    '{{human_handoff_reply}}',
    190,
    true,
    true
  )
on conflict (intent) do update
set keywords = excluded.keywords,
    response_template = excluded.response_template,
    priority = excluded.priority,
    requires_human = excluded.requires_human,
    active = excluded.active,
    updated_at = now();
