-- GDP Clothing Shipping & Delivery administration layer.
alter table public.shipping_profiles add column if not exists origin_location jsonb not null default '{}'::jsonb, add column if not exists product_ids uuid[] not null default '{}'::uuid[], add column if not exists priority integer not null default 100;
alter table public.shipping_rates add column if not exists zone_name text, add column if not exists country_codes text[] not null default array['CA']::text[], add column if not exists province_codes text[] not null default '{}'::text[], add column if not exists postal_patterns text[] not null default '{}'::text[], add column if not exists min_weight_grams numeric, add column if not exists max_weight_grams numeric, add column if not exists rate_source text not null default 'manual', add column if not exists fallback_price numeric, add column if not exists priority integer not null default 100;
create table if not exists public.shipping_packages (id uuid primary key default gen_random_uuid(), name text not null, package_type text not null default 'mailer', length_cm numeric not null default 0, width_cm numeric not null default 0, height_cm numeric not null default 0, empty_weight_grams numeric not null default 0, is_default boolean not null default false, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.delivery_settings (id integer primary key default 1 check (id = 1), local_pickup_enabled boolean not null default true, pickup_name text not null default 'Local Pickup', pickup_location text not null default 'GDP Clothing — Saskatoon', pickup_instructions text, processing_min_days integer not null default 1, processing_max_days integer not null default 2, carrier_rates_enabled boolean not null default false, carrier_name text not null default 'Canada Post', fallback_rate_enabled boolean not null default true, fallback_rate numeric not null default 12.99, updated_at timestamptz not null default now());
insert into public.delivery_settings (id) values (1) on conflict (id) do nothing;
insert into public.shipping_packages (name, package_type, length_cm, width_cm, height_cm, empty_weight_grams, is_default) select 'GDP Poly Mailer', 'mailer', 38, 30, 2, 30, true where not exists (select 1 from public.shipping_packages where is_default = true);
alter table public.shipping_packages enable row level security; alter table public.delivery_settings enable row level security;
create index if not exists shipping_rates_profile_priority_idx on public.shipping_rates(profile_id, active, priority); create index if not exists shipping_rates_method_order_idx on public.shipping_rates(method_code, min_order, max_order);
