-- GDP Clothing order management refinement
-- Additive workflow separation and automatic admin activity history.

begin;

alter table public.orders
  add column if not exists design_status text not null default 'not_required',
  add column if not exists production_status text not null default 'not_started';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'orders_design_status_check'
      and conrelid = 'public.orders'::regclass
  ) then
    alter table public.orders
      add constraint orders_design_status_check
      check (design_status in (
        'not_required','artwork_needed','design_in_progress','proof_ready',
        'awaiting_approval','revision_requested','approved'
      ));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'orders_production_status_check'
      and conrelid = 'public.orders'::regclass
  ) then
    alter table public.orders
      add constraint orders_production_status_check
      check (production_status in (
        'not_started','queued','printing','quality_control','packing','ready','completed'
      ));
  end if;
end
$$;

-- Backfill the independent workflow fields from the legacy combined status.
update public.orders
set design_status = case
  when status = 'artwork_needed' then 'artwork_needed'
  when status = 'design_in_progress' then 'design_in_progress'
  when status = 'proof_ready' then 'proof_ready'
  when status = 'awaiting_approval' then 'awaiting_approval'
  when status = 'revision_requested' then 'revision_requested'
  when status = 'approved' then 'approved'
  else 'not_required'
end;

update public.orders
set production_status = case
  when status = 'production_queue' then 'queued'
  when status = 'printing' then 'printing'
  when status = 'quality_control' then 'quality_control'
  when status = 'packing' then 'packing'
  when status in ('ready_for_pickup','shipped','out_for_delivery','delivered') then 'ready'
  when status = 'completed' then 'completed'
  else 'not_started'
end;

-- Old code mirrored order.status into fulfillment_status. Normalize only those
-- mirrored values so genuine fulfillment values are preserved.
update public.orders
set fulfillment_status = case
  when status = 'ready_for_pickup' then 'ready_for_pickup'
  when status = 'shipped' then 'shipped'
  when status = 'out_for_delivery' then 'out_for_delivery'
  when status = 'delivered' then 'delivered'
  when status = 'completed' then 'fulfilled'
  when status = 'cancelled' then 'cancelled'
  else 'unfulfilled'
end
where fulfillment_status is null
   or fulfillment_status = status
   or fulfillment_status in (
     'draft','pending_payment','paid','payment_failed','artwork_needed',
     'design_in_progress','proof_ready','awaiting_approval','revision_requested',
     'approved','production_queue','printing','quality_control','packing'
   );

create table if not exists public.order_activity_events (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  activity_type text not null,
  field_name text,
  from_value text,
  to_value text,
  note text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists order_activity_events_order_id_idx
  on public.order_activity_events(order_id, created_at desc);

alter table public.order_activity_events enable row level security;

drop policy if exists order_activity_events_admin_read on public.order_activity_events;
create policy order_activity_events_admin_read
on public.order_activity_events for select
using (public.is_admin());

drop policy if exists order_activity_events_admin_insert on public.order_activity_events;
create policy order_activity_events_admin_insert
on public.order_activity_events for insert
with check (public.is_admin());

create or replace function public.log_order_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.status is distinct from new.status then
    insert into public.order_activity_events(
      order_id, actor_user_id, activity_type, field_name, from_value, to_value
    ) values (
      new.id, auth.uid(), 'status_changed', 'status', old.status, new.status
    );
  end if;

  if old.payment_status is distinct from new.payment_status then
    insert into public.order_activity_events(
      order_id, actor_user_id, activity_type, field_name, from_value, to_value
    ) values (
      new.id, auth.uid(), 'payment_changed', 'payment_status', old.payment_status, new.payment_status
    );
  end if;

  if old.fulfillment_status is distinct from new.fulfillment_status then
    insert into public.order_activity_events(
      order_id, actor_user_id, activity_type, field_name, from_value, to_value
    ) values (
      new.id, auth.uid(), 'fulfillment_changed', 'fulfillment_status',
      old.fulfillment_status, new.fulfillment_status
    );
  end if;

  if old.design_status is distinct from new.design_status then
    insert into public.order_activity_events(
      order_id, actor_user_id, activity_type, field_name, from_value, to_value
    ) values (
      new.id, auth.uid(), 'design_changed', 'design_status', old.design_status, new.design_status
    );
  end if;

  if old.production_status is distinct from new.production_status then
    insert into public.order_activity_events(
      order_id, actor_user_id, activity_type, field_name, from_value, to_value
    ) values (
      new.id, auth.uid(), 'production_changed', 'production_status',
      old.production_status, new.production_status
    );
  end if;

  if old.tracking_number is distinct from new.tracking_number
     or old.carrier is distinct from new.carrier then
    insert into public.order_activity_events(
      order_id, actor_user_id, activity_type, field_name, from_value, to_value, metadata
    ) values (
      new.id,
      auth.uid(),
      'tracking_changed',
      'tracking',
      concat_ws(' · ', nullif(old.carrier,''), nullif(old.tracking_number,'')),
      concat_ws(' · ', nullif(new.carrier,''), nullif(new.tracking_number,'')),
      jsonb_build_object('carrier', new.carrier, 'tracking_number', new.tracking_number)
    );
  end if;

  return new;
end;
$$;

drop trigger if exists orders_log_activity on public.orders;
create trigger orders_log_activity
after update of status, payment_status, fulfillment_status, design_status,
  production_status, tracking_number, carrier
on public.orders
for each row execute procedure public.log_order_activity();

commit;
